"use strict";
const test = require("node:test"), assert = require("node:assert/strict"), crypto = require("node:crypto"), sharp = require("sharp");
const { createOperationalCalendarPipelineFixture, PREFIX } = require("./helpers/operational-calendar-pipeline-fixture");
const { dateTime } = require("../src/social/calendar/model");
const chosen = { kind: "image", targets: ["feed"], audioMode: "none" };
async function submit(f, upload, extra = {}) {
  const input = { uploadId: upload.uploadId, idempotencyKey: crypto.randomUUID(), expectedMediaRevision: 0, selection: chosen, ...extra };
  const route = `${PREFIX}/assets/${upload.assetId}/calendar-submissions`;
  const response = await f.post(route, input), body = await response.json();
  assert.equal(response.status, 200, JSON.stringify(body));
  return { input, route, receipt: body.submission };
}
test("durable submission: closed phone and PostgreSQL restart continue preparation into the same calendar; closed gates never send", async t => {
  const f = await createOperationalCalendarPipelineFixture(t);
  await f.executor.prepareRuntime();
  const bytes = await sharp({ create: { width: 120, height: 160, channels: 3, background: "#267376" } }).png().toBuffer();
  const upload = await f.uploadBytes(bytes, "image", "image/png");
  f.setFixtureGate(false); await f.reopen({ restartDatabase: true });
  const { input, route, receipt } = await submit(f, upload);
  assert.equal(receipt.state, "accepted"); assert.equal(receipt.caption, "Conheça nosso trabalho e acompanhe nosso conteúdo.");
  assert.equal(Object.keys((await f.snapshot()).preparation?.jobs || {}).length, 0, "Acceptance performs no preparation side effect");
  assert.ok((await f.current().calendar.list(f.claims)).items.some(item => item.id === receipt.id && item.preparationPending));
  await f.reopen({ restartDatabase: true });
  await f.current().imports.submissions.progress(f.context.companyId);
  await f.preparation.dispatchNext(f.context);
  await f.current().imports.submissions.progress(f.context.companyId);
  const recovered = await f.current().imports.submissions.byKey(f.context, upload.assetId, input.idempotencyKey);
  assert.equal(recovered.state, "scheduled", JSON.stringify(recovered)); assert.equal(recovered.calendarItemId, receipt.id);
  let job = await f.current().calendarStore.update(f.context.companyId, state => state.jobs[receipt.id]);
  assert.equal(job.automaticEnabled, true, "Temporary publication closure does not pause the accepted item");
  assert.equal(job.caption, receipt.caption); assert.equal(job.import.submissionId, receipt.id);
  const calendar = await f.current().calendar.list(f.claims);
  assert.equal(calendar.items.filter(item => item.id === receipt.id).length, 1);
  assert.equal(calendar.items.find(item => item.id === receipt.id).status, "operations_closed");
  const preview = await f.current().scheduling.metadata(f.context, { id: receipt.id });
  assert.equal((await f.request(new URL(preview.variants[0].url).pathname)).status, 200);
  assert.equal((await f.request(`${route}/by-key/${input.idempotencyKey}`, { headers: { Authorization: `Bearer ${f.otherToken}` } })).status, 503);
  f.advance(dateTime(job.date, job.time) - f.clock()); await f.current().calendar.tick(); assert.equal(f.providerCalls.length, 0);
  f.setFixtureGate(true); await f.reopen({ restartDatabase: true });
  await f.current().calendar.tick();
  job = await f.current().calendarStore.update(f.context.companyId, state => state.jobs[receipt.id]);
  assert.equal(job.phase, "published"); assert.equal(f.providerCalls.filter(call => call.operation === "create").length, 1);
  const replay = await (await f.post(route, input)).json(); assert.equal(replay.submission.id, receipt.id);
  assert.equal((await f.current().calendarStore.update(f.context.companyId, state => state.jobs[receipt.id])).phase, "published");
});
test("prepared source reuse, concurrent lost-response recovery and pending cancellation preserve one item and the original art", async t => {
  const f = await createOperationalCalendarPipelineFixture(t), ready = await f.preparePhoto({ selection: chosen });
  const original = await f.current().calendarStore.update(f.context.companyId, state => state.jobs[f.original.id]);
  const { input, route, receipt } = await submit(f, ready, { expectedMediaRevision: 1 });
  const replies = await Promise.all(Array.from({ length: 5 }, () => f.post(route, input)));
  assert.ok(replies.every(response => response.status === 200));
  await f.reopen({ restartDatabase: true });
  await Promise.all([f.current().imports.submissions.progress(f.context.companyId), f.current().imports.submissions.progress(f.context.companyId)]);
  assert.equal(Object.keys((await f.snapshot()).preparation.jobs).length, 1, "Already prepared bytes are reused");
  let job = await f.current().scheduling.get(f.context, receipt.id);
  job = await f.current().scheduling.edit(f.context, job.id, { action: "caption", caption: "Editada depois", revision: job.revision });
  job = await f.current().scheduling.edit(f.context, job.id, { action: "cancel", revision: job.revision });
  assert.equal((await (await f.post(route, input)).json()).submission.state, "cancelled");
  assert.deepEqual(await f.current().calendarStore.update(f.context.companyId, state => state.jobs[f.original.id]), original);
  const pending = await submit(f, ready, { expectedMediaRevision: 1 });
  const before = (await f.current().calendar.list(f.claims)).items.find(item => item.id === pending.receipt.id);
  await f.current().calendar.edit(f.claims, before.id, { action: "cancel", revision: before.revision });
  await f.current().imports.submissions.progress(f.context.companyId);
  assert.equal((await f.current().imports.submissions.byKey(f.context, ready.assetId, pending.input.idempotencyKey)).state, "cancelled");
  assert.equal(await f.current().calendarStore.update(f.context.companyId, state => Boolean(state.jobs[pending.receipt.id])), false);
});
