package br.com.ia4tube.app.feature.create_art

import java.text.Normalizer

data class CreateArtObjective(
    val id: String,
    val label: String,
    val fields: String,
    val photoLabel: String = "",
    val productKey: String = ""
)

data class DynamicObjectiveField(
    val key: String,
    val label: String,
    val type: String,
    val placeholder: String = ""
)

data class CompanyCharacteristic(
    val id: String,
    val label: String
)

object CreateArtCatalog {
    private val blockedRamoKeys = setOf(
        "funeraria",
        "servicos_funerarios",
        "velorio",
        "cemiterio"
    )

    val ramos = listOf(
        "Açaí",
        "Academia",
        "Academia de artes marciais",
        "Academia de dança",
        "Academia de ginástica",
        "Academia de musculação",
        "Academia de natação",
        "Acessórios automotivos",
        "Acessórios femininos",
        "Acessórios para celular",
        "Açougue",
        "Acupuntura",
        "Adega",
        "Administradora de condomínios",
        "Advocacia",
        "Agência de empregos",
        "Agência de marketing",
        "Agência de publicidade",
        "Agência de turismo",
        "Agência digital",
        "Agropecuária",
        "Alinhamento e balanceamento",
        "Aluguel de andaimes",
        "Aluguel de brinquedos",
        "Aluguel de carros",
        "Aluguel de equipamentos",
        "Aluguel de ferramentas",
        "Aluguel de máquinas",
        "Aluguel de roupas",
        "Aluguel de som e iluminação",
        "Amolador",
        "Antiguidades",
        "Aplicação de insulfilm",
        "Ar-condicionado",
        "Armarinho",
        "Aromaterapia",
        "Arquitetura",
        "Artesanato",
        "Assistência técnica",
        "Assistência técnica de celulares",
        "Assistência técnica de computadores",
        "Assistência técnica de eletrodomésticos",
        "Atacadista",
        "Ateliê",
        "Auto elétrica",
        "Auto escola",
        "Auto peças",
        "Auto som",
        "Automação residencial",
        "Avicultura",
        "Bar",
        "Barbearia",
        "Bazar",
        "Bebedouros",
        "Bebidas",
        "Bijuterias",
        "Bicicletaria",
        "Borracharia",
        "Boutique",
        "Brechó",
        "Brindes personalizados",
        "Bronzeamento",
        "Buffet",
        "Cafeteria",
        "Calhas",
        "Cama, mesa e banho",
        "Câmeras de segurança",
        "Camping e pesca",
        "Canil",
        "Capotaria",
        "Carimbos",
        "Carpintaria",
        "Casa de carnes",
        "Casa de festas",
        "Casa de ração",
        "Casa lotérica",
        "Casas pré-fabricadas",
        "Celulares",
        "Centro automotivo",
        "Centro de estética",
        "Centro de treinamento",
        "Cerimonial",
        "Cestas de café da manhã",
        "Chaveiro",
        "Choperia",
        "Churrascaria",
        "Clínica capilar",
        "Clínica de emagrecimento",
        "Clínica de estética",
        "Clínica de exames",
        "Clínica de fisioterapia",
        "Clínica de olhos",
        "Clínica de ortopedia",
        "Clínica de psicologia",
        "Clínica médica",
        "Clínica odontológica",
        "Clínica odontopediátrica",
        "Clínica veterinária",
        "Clube de assinatura",
        "Colchões",
        "Colégio",
        "Comércio de gás",
        "Comunicação visual",
        "Concessionária",
        "Confecção",
        "Confeitaria",
        "Conserto de bicicletas",
        "Conserto de celulares",
        "Conserto de computadores",
        "Conserto de eletrodomésticos",
        "Conserto de máquinas",
        "Conserto de motos",
        "Conserto de roupas",
        "Construtora",
        "Consultoria empresarial",
        "Consultoria financeira",
        "Consultoria de imagem",
        "Contabilidade",
        "Corretora de imóveis",
        "Corretora de seguros",
        "Corte a laser",
        "Cosméticos",
        "Costura",
        "Coworking",
        "Creche",
        "Curso de beleza",
        "Curso de informática",
        "Curso de idiomas",
        "Curso profissionalizante",
        "Decoração",
        "Dedetizadora",
        "Delivery",
        "Dentista",
        "Depilação",
        "Depósito de bebidas",
        "Depósito de construção",
        "Despachante",
        "Designer de interiores",
        "Designer gráfico",
        "Distribuidora",
        "Doceria",
        "Doces personalizados",
        "Drogaria",
        "Elétrica",
        "Eletricista",
        "Eletrônicos",
        "Embalagens",
        "Empório",
        "Encanador",
        "Energia solar",
        "Engenharia",
        "Equipamentos de proteção",
        "Ervanário",
        "Escola",
        "Escola de música",
        "Escola de natação",
        "Escola infantil",
        "Escritório de advocacia",
        "Escritório virtual",
        "Espaço de eventos",
        "Espaço kids",
        "Espetaria",
        "Estacionamento",
        "Estamparia",
        "Estética automotiva",
        "Eventos corporativos",
        "Faculdade",
        "Farmácia",
        "Ferragem",
        "Ferramentaria",
        "Financeira",
        "Fisioterapia",
        "Floricultura",
        "Food truck",
        "Fotografia",
        "Fretes e mudanças",
        "Galeteria",
        "Gráfica",
        "Guincho",
        "Hamburgueria",
        "Hidráulica",
        "Hortifruti",
        "Hospital veterinário",
        "Hotel",
        "Imobiliária",
        "Informática",
        "Instalação elétrica",
        "Instalação hidráulica",
        "Jardinagem",
        "Joalheria",
        "Lanchonete",
        "Lan house",
        "Lavagem de estofados",
        "Lavanderia",
        "Lava-jato",
        "Limpeza de pele",
        "Limpeza pós-obra",
        "Limpeza residencial",
        "Locadora",
        "Loja agropecuária",
        "Loja de acessórios",
        "Loja de artigos religiosos",
        "Loja de artigos esportivos",
        "Loja de bebê",
        "Loja de brinquedos",
        "Loja de calçados",
        "Loja de celular",
        "Loja de conveniência",
        "Loja de cosméticos",
        "Loja de eletrônicos",
        "Loja de embalagens",
        "Loja de ferramentas",
        "Loja de festas",
        "Loja de informática",
        "Loja de materiais elétricos",
        "Loja de móveis",
        "Loja de piscinas",
        "Loja de presentes",
        "Loja de roupas",
        "Loja de suplementos",
        "Loja geek",
        "Madeireira",
        "Manicure",
        "Manutenção de piscinas",
        "Manutenção predial",
        "Marmoraria",
        "Marcenaria",
        "Marmitaria",
        "Marketing visual para empresas",
        "Massoterapia",
        "Materiais de construção",
        "Mecânica automotiva",
        "Mercado",
        "Mercearia",
        "Moda feminina",
        "Moda fitness",
        "Moda infantil",
        "Moda masculina",
        "Motel",
        "Móveis planejados",
        "Nutricionista",
        "Oficina",
        "Oficina de motos",
        "Ortopedia",
        "Ótica",
        "Padaria",
        "Paisagismo",
        "Papelaria",
        "Pastelaria",
        "Perfumaria",
        "Personal trainer",
        "Pet shop",
        "Pilates",
        "Pintura automotiva",
        "Pizzaria",
        "Podologia",
        "Posto de combustível",
        "Pousada",
        "Praia e moda fitness",
        "Produtos de limpeza",
        "Produtos naturais",
        "Psicologia",
        "Quiosque",
        "Refrigeração",
        "Restaurante",
        "Restaurante japonês",
        "Revenda de carros",
        "Rotisseria",
        "Saúde ocupacional",
        "Salgaderia",
        "Salão de beleza",
        "Segurança eletrônica",
        "Seguros",
        "Semijoias",
        "Serviços contábeis",
        "Serviços gerais",
        "Serralheria",
        "Sex shop",
        "Sorveteria",
        "Studio de beleza",
        "Studio de sobrancelhas",
        "Supermercado",
        "Suplementos",
        "Sushi",
        "Tapeçaria",
        "Tatuagem",
        "Tecnologia",
        "Telecom",
        "Temakeria",
        "Terraplanagem",
        "Toldos",
        "Transportadora",
        "Treinamento empresarial",
        "Uniformes",
        "Veterinária",
        "Vidraçaria",
        "Yoga",
        "Acessórios para pets",
        "Adestramento de cães",
        "Aerografia",
        "Alfaiataria",
        "Alimentos congelados",
        "Alimentos funcionais",
        "Alimentos saudáveis",
        "Alongamento de cílios",
        "Animação de festas",
        "Aparelhos auditivos",
        "Aquecedores",
        "Artes gráficas",
        "Assessoria contábil",
        "Assessoria esportiva",
        "Assessoria jurídica",
        "Assessoria para casamentos",
        "Auditoria",
        "Aulas particulares",
        "Balanças comerciais",
        "Balões personalizados",
        "Banca de jornal",
        "Banho e tosa",
        "Barbearia premium",
        "Barraquinha de festa",
        "Baterias automotivas",
        "Berçário",
        "Bolos caseiros",
        "Bolos decorados",
        "Bomboniere",
        "Bordados",
        "Boteco",
        "Brinquedoteca",
        "Cabeleireiro",
        "Cafeteria colonial",
        "Calçados femininos",
        "Calçados infantis",
        "Calçados masculinos",
        "Capas para celular",
        "Capelania",
        "Car lavagem",
        "Carretos",
        "Cartório",
        "Casas de repouso",
        "Cervejaria",
        "Churrasquinho",
        "Climatização",
        "Clínica de vacinas",
        "Clínica geriátrica",
        "Clínica popular",
        "Coach",
        "Cobrança empresarial",
        "Coffee break",
        "Colônia de férias",
        "Comida caseira",
        "Comida fitness",
        "Comida japonesa",
        "Comida mexicana",
        "Comida mineira",
        "Comida nordestina",
        "Comida saudável",
        "Compressor e ferramentas",
        "Condomínios",
        "Conserto de ar-condicionado",
        "Conserto de geladeira",
        "Conserto de impressoras",
        "Conserto de televisão",
        "Consórcio",
        "Contêineres",
        "Controle de pragas",
        "Cozinha industrial",
        "Criação de sites",
        "Cristais e presentes",
        "Cuidadores de idosos",
        "Cupcakes",
        "Cursos online",
        "Day care pet",
        "Delivery de bebidas",
        "Delivery de comida",
        "Desentupidora",
        "Desenvolvimento de software",
        "Desmanche legalizado",
        "Despensa e mercearia",
        "Diagnóstico por imagem",
        "Distribuidora de alimentos",
        "Distribuidora de gás",
        "Distribuidora de higiene",
        "Distribuidora de pneus",
        "Distribuidora de produtos hospitalares",
        "Distribuidora de água",
        "Doces finos",
        "Drones",
        "Educação infantil",
        "Emagrecimento",
        "Enfermagem domiciliar",
        "Envelopamento automotivo",
        "Equipamentos agrícolas",
        "Equipamentos médicos",
        "Ervas medicinais",
        "Escapamentos",
        "Futebol",
        "Escola de costura",
        "Escola de futebol",
        "Escola de robótica",
        "Escola técnica",
        "Esfiharia",
        "Esoterismo",
        "Esquadrias de alumínio",
        "Estética facial",
        "Estética masculina",
        "Estética pet",
        "Estúdio de fotografia",
        "Estúdio de gravação",
        "Estúdio de pilates",
        "Estúdio de tatuagem",
        "Extintores",
        "Fábrica de gelo",
        "Fábrica de móveis",
        "Fábrica de salgados",
        "Festas infantis",
        "Fibra óptica",
        "Fitness boutique",
        "Fonoaudiologia",
        "Forneria",
        "Franquia",
        "Funilaria",
        "Funilaria e pintura",
        "Fábrica de uniformes",
        "Gestão de tráfego",
        "Ginástica laboral",
        "Harmonização facial",
        "Home care",
        "Hospedagem de sites",
        "Hostel",
        "Iluminação",
        "Impermeabilização",
        "Importados",
        "Impressão 3D",
        "Impressão digital",
        "Indústria alimentícia",
        "Indústria têxtil",
        "Influenciador digital",
        "Injeção eletrônica",
        "Instituto de beleza",
        "Internet fibra",
        "Isolamento acústico",
        "Itens personalizados",
        "Jóias",
        "Karaokê",
        "Kits festa",
        "Laboratório de análises",
        "Laboratório óptico",
        "Lareiras",
        "Lavagem a seco",
        "Lavagem de tapetes",
        "Lingerie",
        "Locação de caçambas",
        "Locação de equipamentos",
        "Locação de imóveis",
        "Loja country",
        "Loja de aquários",
        "Loja de artigos para festas",
        "Loja de bolsas",
        "Loja de decoração",
        "Loja de eletrodomésticos",
        "Loja de enxovais",
        "Loja de games",
        "Loja de iluminação",
        "Loja de instrumentos musicais",
        "Loja de lingerie",
        "Loja de maquiagem",
        "Loja de materiais hidráulicos",
        "Loja de motos",
        "Loja de pneus",
        "Loja de utilidades",
        "Loja infantil",
        "Lotérica",
        "Lubrificantes",
        "Luthier",
        "Maquiagem profissional",
        "Máquinas agrícolas",
        "Máquinas de cartão",
        "Máquinas de costura",
        "Máquinas industriais",
        "Marketing político",
        "Mecânica diesel",
        "Mecânica pesada",
        "Medicina do trabalho",
        "Medicina estética",
        "Mei e microempresa",
        "Metalúrgica",
        "Minimercado",
        "Moda evangélica",
        "Moda praia",
        "Montagem de móveis",
        "Móveis rústicos",
        "Oficina de bicicletas",
        "Oficina mecânica",
        "Operadora de internet",
        "Organização de festas",
        "Organização residencial",
        "Padaria artesanal",
        "Pamonharia",
        "Panificadora",
        "Papel de parede",
        "Parafusos e ferramentas",
        "Pastifício",
        "Peixaria",
        "Perícia técnica",
        "Personalizados",
        "Pescados",
        "Petiscaria",
        "Pintura predial",
        "Pintura residencial",
        "Pisos e revestimentos",
        "Pizzaria delivery",
        "Planejados",
        "Plano de saúde",
        "Polimento automotivo",
        "Portões automáticos",
        "Prótese dentária",
        "Psicopedagogia",
        "Quiropraxia",
        "Reabilitação física",
        "Recarga de cartuchos",
        "Recarga de extintores",
        "Reciclagem",
        "Refeições coletivas",
        "Reforço escolar",
        "Relojoaria",
        "Retífica",
        "Retífica de motores",
        "Roupas profissionais",
        "Salão infantil",
        "Sapataria",
        "Segurança do trabalho",
        "Seguro auto",
        "Seguro residencial",
        "Serviço de guincho",
        "Serviço de instalação",
        "Serviço de pintura",
        "Serviço de portaria",
        "Serviço de reforma",
        "Serviço de solda",
        "Serviços administrativos",
        "Serviços de limpeza",
        "Silkscreen",
        "Som automotivo",
        "Spa",
        "Supermercado de bairro",
        "Tabacaria",
        "Tapeçaria automotiva",
        "Terapia holística",
        "Terapia ocupacional",
        "Tintas",
        "Topografia",
        "Transportes executivos",
        "Trattoria",
        "Turismo rural",
        "Uniformes escolares",
        "Uniformes profissionais",
        "Utensílios domésticos",
        "Venda de motos",
        "Venda de pneus",
        "Venda de veículos",
        "Vistoria veicular",
        "Visual merchandising",
        "Vitrines",
        "Web design",
        "Xerox e cópias",
        "Zeladoria"
    ).filterNot(::isBlockedRamo)

    val objetivosGerais = listOf(
        CreateArtObjective(id = "divulgar_trabalho", label = "Quero divulgar meu trabalho", fields = "servico"),
        CreateArtObjective(id = "parecer_profissional", label = "Quero parecer mais profissional", fields = "profissional"),
        CreateArtObjective(id = "chamar_atencao_instagram", label = "Quero chamar atenção no Instagram", fields = "instagram"),
        CreateArtObjective(id = "divulgar_promocao", label = "Quero divulgar uma promoção", fields = "promocao"),
        CreateArtObjective(id = "mostrar_produtos", label = "Quero mostrar meus produtos", fields = "produto"),
        CreateArtObjective(id = "transmitir_confianca", label = "Quero transmitir confiança", fields = "confianca"),
        CreateArtObjective(id = "atrair_clientes", label = "Quero atrair mais clientes", fields = "clientes"),
        CreateArtObjective(id = "receber_mensagens", label = "Quero receber mais mensagens", fields = "mensagens"),
        CreateArtObjective(id = "destacar_empresa", label = "Quero destacar minha empresa", fields = "empresa")
    )

    private val caracteristicasGerais = listOf(
        CompanyCharacteristic(id = "aceita_pix", label = "Aceitamos Pix"),
        CompanyCharacteristic(id = "parcela_cartao", label = "Parcelamos no cartão"),
        CompanyCharacteristic(id = "agendamento", label = "Atendimento por agendamento"),
        CompanyCharacteristic(id = "estacionamento", label = "Estacionamento"),
        CompanyCharacteristic(id = "atendimento_24h", label = "Atendimento 24 horas"),
        CompanyCharacteristic(id = "domingos", label = "Atendimento aos domingos"),
        CompanyCharacteristic(id = "retirada_local", label = "Retirada no local"),
        CompanyCharacteristic(id = "atendimento_online", label = "Atendimento online")
    )

    private val caracteristicasPorCategoria = mapOf(
        "alimentacao" to listOf(
            CompanyCharacteristic(id = "tem_delivery", label = "Temos delivery"),
            CompanyCharacteristic(id = "retirada_balcao", label = "Retirada no balcão"),
            CompanyCharacteristic(id = "drive_thru", label = "Drive-thru"),
            CompanyCharacteristic(id = "aceita_encomendas", label = "Aceitamos encomendas"),
            CompanyCharacteristic(id = "area_infantil", label = "Área infantil")
        ),
        "saude" to listOf(
            CompanyCharacteristic(id = "agendamento", label = "Atendimento por agendamento"),
            CompanyCharacteristic(id = "urgencia", label = "Atendimento de urgência"),
            CompanyCharacteristic(id = "convenios", label = "Convênios"),
            CompanyCharacteristic(id = "estacionamento", label = "Estacionamento"),
            CompanyCharacteristic(id = "avaliacao_gratuita", label = "Avaliação gratuita")
        ),
        "beleza" to listOf(
            CompanyCharacteristic(id = "agendamento", label = "Atendimento por agendamento"),
            CompanyCharacteristic(id = "avaliacao_gratuita", label = "Avaliação gratuita"),
            CompanyCharacteristic(id = "procedimentos_esteticos", label = "Procedimentos estéticos"),
            CompanyCharacteristic(id = "atendimento_feminino", label = "Atendimento feminino"),
            CompanyCharacteristic(id = "atendimento_masculino", label = "Atendimento masculino")
        ),
        "varejo" to listOf(
            CompanyCharacteristic(id = "troca_facilitada", label = "Troca facilitada"),
            CompanyCharacteristic(id = "provador", label = "Provador"),
            CompanyCharacteristic(id = "parcela_cartao", label = "Parcelamos no cartão"),
            CompanyCharacteristic(id = "entrega_local", label = "Entrega local"),
            CompanyCharacteristic(id = "retirada_loja", label = "Retirada na loja")
        ),
        "automotivo" to listOf(
            CompanyCharacteristic(id = "agendamento", label = "Atendimento por agendamento"),
            CompanyCharacteristic(id = "orcamento", label = "Orçamento"),
            CompanyCharacteristic(id = "retirada_local", label = "Retirada no local"),
            CompanyCharacteristic(id = "garantia_servico", label = "Garantia do serviço"),
            CompanyCharacteristic(id = "estacionamento", label = "Estacionamento")
        ),
        "servicos_profissionais" to listOf(
            CompanyCharacteristic(id = "atendimento_online", label = "Atendimento online"),
            CompanyCharacteristic(id = "agendamento", label = "Atendimento por agendamento"),
            CompanyCharacteristic(id = "orcamento", label = "Orçamento"),
            CompanyCharacteristic(id = "visita_tecnica", label = "Visita técnica"),
            CompanyCharacteristic(id = "contrato_servico", label = "Contrato de serviço")
        )
    )

    private val ramoCategorias = mapOf(
        "hamburgueria" to "alimentacao",
        "pizzaria" to "alimentacao",
        "lanchonete" to "alimentacao",
        "restaurante" to "alimentacao",
        "confeitaria" to "alimentacao",
        "doceria" to "alimentacao",
        "marmitaria" to "alimentacao",
        "vidracaria" to "casa_servicos",
        "marcenaria" to "casa_servicos",
        "serralheria" to "casa_servicos",
        "marmoraria" to "casa_servicos",
        "construtora" to "casa_servicos",
        "barbearia" to "beleza",
        "salao_de_beleza" to "beleza",
        "manicure" to "beleza",
        "clinica_de_estetica" to "beleza",
        "odontologia" to "saude",
        "dentista" to "saude",
        "clinica_odontologica" to "saude",
        "clinica_medica" to "saude",
        "fisioterapia" to "saude",
        "pet_shop" to "pet",
        "clinica_veterinaria" to "pet",
        "banho_e_tosa" to "pet",
        "academia" to "fitness",
        "pilates" to "fitness",
        "personal_trainer" to "fitness",
        "loja_de_roupas" to "varejo",
        "loja_de_calcados" to "varejo",
        "loja_de_acessorios" to "varejo",
        "mercado" to "varejo",
        "supermercado" to "varejo",
        "oficina" to "automotivo",
        "mecanica_automotiva" to "automotivo",
        "lava_jato" to "automotivo",
        "borracharia" to "automotivo",
        "imobiliaria" to "servicos_profissionais",
        "advocacia" to "servicos_profissionais",
        "contabilidade" to "servicos_profissionais",
        "marketing_visual_para_empresas" to "servicos_profissionais",
        "escola" to "educacao",
        "creche" to "educacao",
        "curso_de_idiomas" to "educacao"
    )

    private val categoriaKeywords = mapOf(
        "alimentacao" to listOf(
            "acai",
            "acougue",
            "adega",
            "alimento",
            "assado",
            "bebida",
            "biscoito",
            "bolo",
            "bomboniere",
            "bar",
            "boteco",
            "buffet",
            "cafe",
            "cafeteria",
            "carnes",
            "casa_de_festas",
            "cervejaria",
            "chapa",
            "chocolate",
            "choperia",
            "churrascaria",
            "churrasquinho",
            "comida",
            "confeitaria",
            "cozinha",
            "cupcake",
            "delivery",
            "doceria",
            "doce",
            "emporio",
            "esfiharia",
            "espetaria",
            "food_truck",
            "forneria",
            "frango",
            "frutaria",
            "galeteria",
            "hamburgueria",
            "hortifruti",
            "japones",
            "lanchonete",
            "lanche",
            "marmitaria",
            "mercado",
            "mercearia",
            "mexicana",
            "mineira",
            "nordestina",
            "padaria",
            "pamonharia",
            "panificadora",
            "pastelaria",
            "peixaria",
            "pescados",
            "petiscaria",
            "pizza",
            "pizzaria",
            "produtos_naturais",
            "queijaria",
            "refeicoes",
            "restaurante",
            "rodizio",
            "rotisseria",
            "salgaderia",
            "salgado",
            "saudavel",
            "sorveteria",
            "sorvete",
            "sushi",
            "temakeria",
            "trattoria",
            "varejo_alimentar",
            "coffee_break",
            "fabrica_de_gelo",
            "festas_infantis",
            "industria_alimenticia",
            "karaoke",
            "pastificio",
            "quiosque"
        ),
        "automotivo" to listOf(
            "alinhamento",
            "auto",
            "automotivo",
            "balanceamento",
            "bateria",
            "bicicletaria",
            "bicicletas",
            "borracharia",
            "car_lavagem",
            "carros",
            "capotaria",
            "centro_automotivo",
            "concessionaria",
            "desmanche",
            "diesel",
            "escapamento",
            "estetica_automotiva",
            "funilaria",
            "garagem",
            "guincho",
            "injecao",
            "insulfilm",
            "lava_jato",
            "lavagem_ecologica",
            "lubrificantes",
            "mecanica",
            "motos",
            "oficina",
            "pintura_automotiva",
            "pneus",
            "polimento",
            "posto_de_combustivel",
            "retifica",
            "som_automotivo",
            "veicular",
            "veiculos",
            "vistoria"
        ),
        "beleza" to listOf(
            "alongamento_de_cilios",
            "barbearia",
            "beleza",
            "bronzeamento",
            "cabeleireiro",
            "capilar",
            "cilios",
            "clinica_de_estetica",
            "cosmeticos",
            "depilacao",
            "design_de_sobrancelhas",
            "drenagem",
            "estetica",
            "harmonizacao",
            "instituto_de_beleza",
            "limpeza_de_pele",
            "manicure",
            "maquiagem",
            "micropigmentacao",
            "perfumaria",
            "salao",
            "sobrancelhas",
            "spa",
            "studio_de_beleza",
            "tatuagem"
        ),
        "casa_servicos" to listOf(
            "aluguel_de_andaimes",
            "aquecedores",
            "ar_condicionado",
            "arquitetura",
            "automacao_residencial",
            "banquetas",
            "blocos",
            "bobinagem",
            "calhas",
            "calculista",
            "cameras_de_seguranca",
            "casa_de_racao",
            "casas_pre_fabricadas",
            "amolador",
            "aerografia",
            "carpintaria",
            "chaveiro",
            "climatizacao",
            "comercio_de_gas",
            "concretagem",
            "conserto_de_eletrodomesticos",
            "conserto_de_geladeira",
            "conserto_de_televisao",
            "construcao",
            "construtora",
            "conteineres",
            "controle_de_pragas",
            "corte_a_laser",
            "cortinas",
            "decoracao",
            "dedetizadora",
            "deposito_de_construcao",
            "desentupidora",
            "designer_de_interiores",
            "drywall",
            "eletrica",
            "eletricista",
            "encanador",
            "energia_solar",
            "engenharia",
            "esquadrias",
            "ferragem",
            "ferragens",
            "ferramentas",
            "gesso",
            "hidraulica",
            "impermeabilizacao",
            "instalacao",
            "janelas",
            "jardinagem",
            "lavagem_a_seco",
            "lavagem_de_estofados",
            "lavanderia",
            "limpeza",
            "limpeza_pos_obra",
            "madeireira",
            "manutencao",
            "maquetes",
            "marmoraria",
            "marcenaria",
            "materiais_de_construcao",
            "moveis",
            "móveis",
            "paisagismo",
            "papel_de_parede",
            "pintura_predial",
            "pintura_residencial",
            "piscinas",
            "pisos",
            "planejados",
            "portoes",
            "projetos_arquitetonicos",
            "projetos_eletricos",
            "reforma",
            "extintores",
            "ferramentaria",
            "iluminacao",
            "isolamento_acustico",
            "lareiras",
            "locacao_de_cacambas",
            "metalurgica",
            "pintura",
            "recarga_de_extintores",
            "refrigeracao",
            "seguranca_eletronica",
            "serralheria",
            "solda",
            "tapecaria",
            "tapetes",
            "terraplanagem",
            "tintas",
            "zeladoria",
            "toldos",
            "topografia",
            "usinagem",
            "vidracaria",
            "vitrines"
        ),
        "educacao" to listOf(
            "acompanhamento_escolar",
            "aulas",
            "bercario",
            "brinquedoteca",
            "colegio",
            "colonia_de_ferias",
            "creche",
            "curso",
            "cursos",
            "educacao",
            "escola",
            "faculdade",
            "infantil",
            "instituto_de_idiomas",
            "ingles",
            "matriculas",
            "preparatoria",
            "reforco_escolar",
            "robótica",
            "tecnica",
            "treinamento"
        ),
        "fitness" to listOf(
            "academia",
            "assessoria_esportiva",
            "danca",
            "fitness",
            "funcional",
            "ginastica",
            "musculacao",
            "natacao",
            "personal_trainer",
            "pilates",
            "praia_e_moda_fitness",
            "suplementos",
            "yoga"
        ),
        "pet" to listOf(
            "adestramento",
            "alimentos_para_pets",
            "avicultura",
            "banho_e_tosa",
            "canil",
            "clinica_para_pets",
            "clinica_veterinaria",
            "hospital_veterinario",
            "hotelaria_pet",
            "pet",
            "pet_shop",
            "racao",
            "veterinaria",
            "veterinario"
        ),
        "saude" to listOf(
            "acupuntura",
            "analises_clinicas",
            "aparelhos_auditivos",
            "atendimento_domiciliar",
            "casas_de_repouso",
            "centro_de_diagnostico",
            "clinica",
            "cuidador",
            "dentista",
            "diagnostico",
            "emagrecimento",
            "enfermagem",
            "exames",
            "farmacia",
            "fisioterapia",
            "fonoaudiologia",
            "geriatrica",
            "home_care",
            "drogaria",
            "ervanario",
            "laboratorio",
            "medicina",
            "medico",
            "nutricionista",
            "odontologia",
            "odontologica",
            "ortopedia",
            "otica",
            "podologia",
            "protese_dentaria",
            "psicologia",
            "psicopedagogia",
            "quiropraxia",
            "reabilitacao",
            "saude",
            "terapia",
            "vacinas"
        ),
        "servicos_profissionais" to listOf(
            "administradora",
            "advocacia",
            "advogado",
            "agencia",
            "aluguel_de_som",
            "animacao_de_festas",
            "arquitetura",
            "assessoria",
            "auditoria",
            "balancas",
            "capelania",
            "carretos",
            "cartorio",
            "cerimonial",
            "clube_de_assinatura",
            "coach",
            "cobranca",
            "comunicacao_visual",
            "condominios",
            "conserto_de_computadores",
            "conserto_de_impressoras",
            "consignado",
            "consorcio",
            "consultoria",
            "contabilidade",
            "contabeis",
            "corretora",
            "coworking",
            "criacao_de_sites",
            "credito",
            "despachante",
            "designer_grafico",
            "distribuidora",
            "drones",
            "e_commerce",
            "emprestimos",
            "escritorio_virtual",
            "estacionamento",
            "estudio_de_gravacao",
            "eventos",
            "financeira",
            "fotografia",
            "franquia",
            "gestao",
            "grafica",
            "hospedagem_de_sites",
            "hostel",
            "hotel",
            "imobiliaria",
            "influenciador",
            "internet_fibra",
            "lan_house",
            "locadora",
            "marketing",
            "mei",
            "motel",
            "operadora_de_internet",
            "organizacao",
            "pousada",
            "publicidade",
            "reciclagem",
            "rh",
            "fibra_optica",
            "seguranca_do_trabalho",
            "seguros",
            "seguro_residencial",
            "servico_de_portaria",
            "servicos_administrativos",
            "servicos_gerais",
            "software",
            "tecnologia",
            "telecom",
            "transportadora",
            "transportes_executivos",
            "visual_merchandising",
            "turismo",
            "web_design"
        ),
        "varejo" to listOf(
            "acessorios",
            "agropecuaria",
            "antiguidades",
            "armarinho",
            "artesanato",
            "artigos",
            "atacadista",
            "atelie",
            "bazar",
            "baloes",
            "banca_de_jornal",
            "bebedouros",
            "bijuterias",
            "bordados",
            "boutique",
            "brecho",
            "brindes",
            "brinquedos",
            "calcados",
            "cama_mesa",
            "camping",
            "carimbos",
            "celular",
            "colchoes",
            "confeccao",
            "conveniencia",
            "cosmeticos",
            "costura",
            "country",
            "eletronicos",
            "embalagens",
            "enxovais",
            "estamparia",
            "equipamentos",
            "ferramentas",
            "floricultura",
            "games",
            "geek",
            "informatica",
            "instrumentos",
            "alfaiataria",
            "importados",
            "impressao",
            "industria_textil",
            "itens_personalizados",
            "joalheria",
            "joias",
            "kits_festa",
            "lingerie",
            "livraria",
            "loja",
            "lotérica",
            "luthier",
            "maquinas",
            "moda",
            "papelaria",
            "personalizados",
            "recarga_de_cartuchos",
            "relojoaria",
            "sapataria",
            "silkscreen",
            "utensilios_domesticos",
            "xerox",
            "perfumaria",
            "presentes",
            "produtos_de_limpeza",
            "religiosos",
            "roupas",
            "semijoias",
            "sex_shop",
            "suplementos",
            "tabacaria",
            "uniformes",
            "utilidades",
            "vendas_online"
        )
    )

    private val ramoAliases = mapOf(
        "Marketing visual para empresas" to listOf(
            "ia4tube",
            "design",
            "post",
            "posts",
            "instagram",
            "omascote",
            "o mascote",
            "mascote",
            "futebol",
            "arte esportiva",
            "arte automatica",
            "artes automaticas",
            "criacao de artes",
            "marketing visual"
        )
    )

    private val objetivosPorCategoria = mapOf(
        "alimentacao" to listOf(
            CreateArtObjective(id = "divulgar_delivery", label = "Quero divulgar delivery", fields = "delivery"),
            CreateArtObjective(id = "divulgar_combo", label = "Quero divulgar combo", fields = "combo"),
            CreateArtObjective(id = "mostrar_cardapio", label = "Quero mostrar meu cardápio", fields = "cardapio")
        ),
        "casa_servicos" to listOf(
            CreateArtObjective(id = "mostrar_projetos", label = "Quero mostrar meus projetos", fields = "projeto"),
            CreateArtObjective(id = "divulgar_orcamento", label = "Quero divulgar orçamento", fields = "orcamento"),
            CreateArtObjective(id = "destacar_acabamento", label = "Quero destacar acabamento", fields = "acabamento")
        ),
        "beleza" to listOf(
            CreateArtObjective(id = "divulgar_servicos_beleza", label = "Quero divulgar meus serviços", fields = "servico"),
            CreateArtObjective(id = "destacar_espaco", label = "Quero destacar meu espaço", fields = "espaco"),
            CreateArtObjective(id = "mostrar_antes_depois", label = "Quero mostrar antes e depois", fields = "antes_depois")
        ),
        "saude" to listOf(
            CreateArtObjective(id = "transmitir_confianca_saude", label = "Quero transmitir confiança", fields = "confianca"),
            CreateArtObjective(id = "apresentar_atendimento", label = "Quero apresentar meu atendimento", fields = "atendimento"),
            CreateArtObjective(id = "divulgar_especialidade", label = "Quero divulgar uma especialidade", fields = "especialidade")
        ),
        "pet" to listOf(
            CreateArtObjective(id = "divulgar_banho_tosa", label = "Quero divulgar banho e tosa", fields = "pet_servico"),
            CreateArtObjective(id = "mostrar_cuidado_pet", label = "Quero mostrar cuidado com os pets", fields = "confianca")
        ),
        "fitness" to listOf(
            CreateArtObjective(id = "divulgar_aulas", label = "Quero divulgar aulas", fields = "aulas"),
            CreateArtObjective(id = "mostrar_estrutura", label = "Quero mostrar minha estrutura", fields = "espaco")
        ),
        "varejo" to listOf(
            CreateArtObjective(id = "mostrar_novidades", label = "Quero mostrar novidades", fields = "produto"),
            CreateArtObjective(id = "divulgar_colecao", label = "Quero divulgar uma coleção", fields = "colecao")
        ),
        "automotivo" to listOf(
            CreateArtObjective(id = "divulgar_servico_auto", label = "Quero divulgar um serviço", fields = "servico_auto"),
            CreateArtObjective(id = "mostrar_resultado_auto", label = "Quero mostrar resultado do serviço", fields = "antes_depois")
        ),
        "servicos_profissionais" to listOf(
            CreateArtObjective(id = "apresentar_servico", label = "Quero apresentar meu serviço", fields = "servico"),
            CreateArtObjective(id = "transmitir_autoridade", label = "Quero transmitir autoridade", fields = "profissional")
        ),
        "educacao" to listOf(
            CreateArtObjective(id = "divulgar_matriculas", label = "Quero divulgar matrículas", fields = "matriculas"),
            CreateArtObjective(id = "apresentar_curso", label = "Quero apresentar um curso", fields = "curso")
        )
    )

    private val objetivosPorNicho = mapOf(
        "futebol" to listOf(
            CreateArtObjective(id = "treino", label = "Dia de Treino", fields = "", productKey = "treino"),
            CreateArtObjective(id = "futebol_mascote_3d", label = "Mascote 3D", fields = "", productKey = "mascote_uniforme"),
            CreateArtObjective(id = "futebol_escudo_3d", label = "Escudo 3D", fields = "", productKey = "escudo3d"),
            CreateArtObjective(id = "futebol_resultado", label = "Resultado", fields = "", productKey = "resultado"),
            CreateArtObjective(id = "futebol_proximo_jogo", label = "Próximo Jogo", fields = "", productKey = "proximo_jogo"),
            CreateArtObjective(id = "futebol_escalacao", label = "Escalação", fields = "", productKey = "escalacao"),
            CreateArtObjective(id = "futebol_contratacao", label = "Contratação", fields = "", productKey = "contratacao"),
            CreateArtObjective(id = "futebol_patrocinador", label = "Patrocinador", fields = "", productKey = "patrocinador")
        ),
        "hamburgueria" to listOf(
            CreateArtObjective(id = "divulgar_lanche", label = "Quero divulgar meu lanche", fields = "lanche", photoLabel = "Foto do lanche"),
            CreateArtObjective(id = "divulgar_combo_hamburgueria", label = "Quero divulgar combo", fields = "combo", photoLabel = "Foto do combo")
        ),
        "pizzaria" to listOf(
            CreateArtObjective(id = "divulgar_pizza", label = "Quero divulgar minha pizza", fields = "pizza", photoLabel = "Foto da pizza"),
            CreateArtObjective(id = "divulgar_rodizio", label = "Quero divulgar rodízio", fields = "rodizio")
        ),
        "vidracaria" to listOf(
            CreateArtObjective(id = "divulgar_box_banheiro", label = "Quero divulgar box de banheiro", fields = "vidro_box", photoLabel = "Foto do projeto ou referência"),
            CreateArtObjective(id = "mostrar_projetos_vidracaria", label = "Quero mostrar meus projetos", fields = "vidro_projeto", photoLabel = "Foto do projeto")
        ),
        "barbearia" to listOf(
            CreateArtObjective(id = "divulgar_cortes", label = "Quero divulgar cortes", fields = "corte", photoLabel = "Foto do corte ou espaço"),
            CreateArtObjective(id = "destacar_espaco_barbearia", label = "Quero destacar meu espaço", fields = "espaco")
        ),
        "pet_shop" to listOf(
            CreateArtObjective(id = "divulgar_banho_tosa_pet", label = "Quero divulgar banho e tosa", fields = "pet_servico", photoLabel = "Fotos dos pets ou do espaço")
        ),
        "marketing_visual_para_empresas" to listOf(
            CreateArtObjective(id = "divulgar_servicos_marketing_visual", label = "Quero divulgar meus serviços", fields = "marketing_visual"),
            CreateArtObjective(id = "mostrar_funcionamento_ia4tube", label = "Quero mostrar como funciona o IA4Tube", fields = "marketing_visual"),
            CreateArtObjective(id = "explicar_beneficio_ia", label = "Quero explicar o benefício da IA", fields = "marketing_visual"),
            CreateArtObjective(id = "atrair_empresas_locais", label = "Quero atrair empresas locais", fields = "marketing_visual"),
            CreateArtObjective(id = "parecer_profissional_marketing_visual", label = "Quero parecer mais profissional", fields = "marketing_visual"),
            CreateArtObjective(id = "mostrar_antes_depois_marketing_visual", label = "Quero mostrar antes e depois", fields = "marketing_visual"),
            CreateArtObjective(id = "divulgar_artes_automaticas", label = "Quero divulgar criação de artes automáticas", fields = "marketing_visual"),
            CreateArtObjective(id = "fortalecer_marca_marketing_visual", label = "Quero fortalecer minha marca", fields = "marketing_visual"),
            CreateArtObjective(id = "gerar_interesse_instagram", label = "Quero gerar interesse no Instagram", fields = "marketing_visual"),
            CreateArtObjective(id = "receber_whatsapp_marketing_visual", label = "Quero receber mensagens no WhatsApp", fields = "marketing_visual")
        )
    )

    val camposDinamicosPorObjetivo = mapOf(
        "servico" to listOf(
            DynamicObjectiveField(key = "servico_principal", label = "Serviço principal", type = "text", placeholder = "Ex: instalação, atendimento, manutenção"),
            DynamicObjectiveField(key = "diferencial", label = "Diferencial", type = "text", placeholder = "Ex: atendimento rápido, garantia, experiência")
        ),
        "corte" to listOf(
            DynamicObjectiveField(key = "tipo_corte", label = "Tipo de corte", type = "text", placeholder = "Ex: degradê, social, navalhado"),
            DynamicObjectiveField(key = "combo_barbearia", label = "Combo ou serviço adicional", type = "text", placeholder = "Ex: corte + barba, sobrancelha, acabamento"),
            DynamicObjectiveField(key = "preco", label = "Preço", type = "text", placeholder = "Opcional")
        ),
        "profissional" to listOf(
            DynamicObjectiveField(key = "tempo_mercado", label = "Tempo de mercado", type = "text", placeholder = "Ex: 10 anos de experiência"),
            DynamicObjectiveField(key = "credenciais", label = "Credenciais ou diferenciais", type = "textarea", placeholder = "Ex: equipe especializada, certificações, estrutura")
        ),
        "instagram" to listOf(
            DynamicObjectiveField(key = "mensagem_principal", label = "Mensagem principal", type = "text", placeholder = "Ex: conheça nossos serviços"),
            DynamicObjectiveField(key = "tom_visual", label = "Tom visual desejado", type = "text", placeholder = "Ex: moderno, elegante, divertido")
        ),
        "promocao" to listOf(
            DynamicObjectiveField(key = "promocao", label = "Promoção", type = "text", placeholder = "Ex: 20% de desconto nesta semana"),
            DynamicObjectiveField(key = "validade", label = "Validade", type = "text", placeholder = "Ex: até sábado")
        ),
        "produto" to listOf(
            DynamicObjectiveField(key = "produto_principal", label = "Produto principal", type = "text", placeholder = "Ex: vestido, suplemento, acessório"),
            DynamicObjectiveField(key = "beneficios", label = "Benefícios ou características", type = "textarea", placeholder = "Ex: confortável, resistente, pronta entrega")
        ),
        "confianca" to listOf(
            DynamicObjectiveField(key = "prova_confianca", label = "O que transmite confiança?", type = "textarea", placeholder = "Ex: equipe qualificada, garantia, avaliações, ambiente seguro")
        ),
        "clientes" to listOf(
            DynamicObjectiveField(key = "publico_desejado", label = "Público que deseja alcançar", type = "text", placeholder = "Ex: famílias, empresas, moradores da região")
        ),
        "mensagens" to listOf(
            DynamicObjectiveField(key = "motivo_contato", label = "Motivo para chamar no WhatsApp", type = "text", placeholder = "Ex: pedir orçamento, agendar, tirar dúvidas")
        ),
        "marketing_visual" to listOf(
            DynamicObjectiveField(key = "servico_principal", label = "Serviço principal", type = "text", placeholder = "Ex: criação automática de artes para empresas"),
            DynamicObjectiveField(key = "publico_alvo", label = "Público-alvo", type = "text", placeholder = "Ex: pequenos negócios, comércios locais, prestadores de serviço"),
            DynamicObjectiveField(key = "beneficio_principal", label = "Benefício principal", type = "textarea", placeholder = "Ex: receber uma arte profissional pronta para postar"),
            DynamicObjectiveField(key = "frase_impacto", label = "Frase de impacto", type = "text", placeholder = "Ex: sua empresa com cara profissional nas redes"),
            DynamicObjectiveField(key = "chamada_whatsapp", label = "Chamada para WhatsApp", type = "text", placeholder = "Ex: chame no WhatsApp e peça sua arte"),
            DynamicObjectiveField(key = "prova_resultado", label = "Prova/resultado/exemplo", type = "textarea", placeholder = "Ex: antes e depois, exemplo de nicho, arte pronta"),
            DynamicObjectiveField(key = "observacao_arte", label = "Observação da arte", type = "textarea", placeholder = "Detalhe visual ou mensagem que precisa aparecer")
        ),
        "empresa" to listOf(
            DynamicObjectiveField(key = "destaque_empresa", label = "Principal destaque da empresa", type = "textarea", placeholder = "Ex: tradição, localização, equipe, atendimento")
        ),
        "delivery" to listOf(
            DynamicObjectiveField(key = "area_entrega", label = "Área de entrega", type = "text", placeholder = "Ex: entregamos no centro e bairros próximos"),
            DynamicObjectiveField(key = "pedido_minimo", label = "Pedido mínimo ou condição", type = "text", placeholder = "Opcional")
        ),
        "combo" to listOf(
            DynamicObjectiveField(key = "nome_combo", label = "Nome do combo", type = "text", placeholder = "Ex: Combo casal"),
            DynamicObjectiveField(key = "itens_combo", label = "Itens do combo", type = "textarea", placeholder = "Ex: 2 lanches, batata e refrigerante"),
            DynamicObjectiveField(key = "preco", label = "Preço", type = "text", placeholder = "Ex: R$ 49,90")
        ),
        "cardapio" to listOf(
            DynamicObjectiveField(key = "itens_destaque", label = "Itens em destaque", type = "textarea", placeholder = "Ex: pratos, sabores, bebidas")
        ),
        "lanche" to listOf(
            DynamicObjectiveField(key = "nome_lanche", label = "Nome do lanche", type = "text", placeholder = "Ex: X-Bacon especial"),
            DynamicObjectiveField(key = "preco", label = "Preço", type = "text", placeholder = "Ex: R$ 29,90"),
            DynamicObjectiveField(key = "ingredientes", label = "Ingredientes", type = "textarea", placeholder = "Ex: pão brioche, burger, cheddar, bacon"),
            DynamicObjectiveField(key = "delivery", label = "Tem delivery?", type = "text", placeholder = "Ex: sim, pelo WhatsApp")
        ),
        "pizza" to listOf(
            DynamicObjectiveField(key = "sabor_pizza", label = "Sabor da pizza", type = "text", placeholder = "Ex: calabresa, frango com catupiry"),
            DynamicObjectiveField(key = "preco", label = "Preço", type = "text", placeholder = "Ex: R$ 39,90"),
            DynamicObjectiveField(key = "tamanho", label = "Tamanho", type = "text", placeholder = "Ex: grande, família")
        ),
        "rodizio" to listOf(
            DynamicObjectiveField(key = "dias_horarios", label = "Dias e horários", type = "text", placeholder = "Ex: terça a quinta, das 19h às 23h"),
            DynamicObjectiveField(key = "valor", label = "Valor", type = "text", placeholder = "Ex: R$ 59,90 por pessoa")
        ),
        "projeto" to listOf(
            DynamicObjectiveField(key = "tipo_projeto", label = "Tipo de projeto", type = "text", placeholder = "Ex: banheiro, varanda, fachada"),
            DynamicObjectiveField(key = "descricao_projeto", label = "Descrição do projeto", type = "textarea", placeholder = "Conte o que aparece na foto ou referência")
        ),
        "vidro_box" to listOf(
            DynamicObjectiveField(key = "tipo_vidro", label = "Tipo do vidro", type = "text", placeholder = "Ex: temperado, fumê, jateado"),
            DynamicObjectiveField(key = "acabamento", label = "Acabamento", type = "text", placeholder = "Ex: inox, roldanas aparentes, perfil preto"),
            DynamicObjectiveField(key = "medida_ou_condicao", label = "Medida ou condição", type = "text", placeholder = "Ex: sob medida, orçamento grátis")
        ),
        "vidro_projeto" to listOf(
            DynamicObjectiveField(key = "tipo_vidro", label = "Tipo do vidro", type = "text", placeholder = "Ex: temperado, laminado, espelho"),
            DynamicObjectiveField(key = "acabamento", label = "Acabamento", type = "text", placeholder = "Ex: alumínio, inox, preto fosco"),
            DynamicObjectiveField(key = "descricao_projeto", label = "Descrição do projeto", type = "textarea", placeholder = "Ex: fechamento de sacada, box, espelho")
        ),
        "acabamento" to listOf(
            DynamicObjectiveField(key = "material", label = "Material ou acabamento", type = "text", placeholder = "Ex: vidro temperado, madeira, aço"),
            DynamicObjectiveField(key = "detalhes_acabamento", label = "Detalhes do acabamento", type = "textarea", placeholder = "Ex: cor, textura, brilho, instalação")
        ),
        "espaco" to listOf(
            DynamicObjectiveField(key = "ambiente", label = "Ambiente que quer destacar", type = "text", placeholder = "Ex: recepção, área de atendimento, salão"),
            DynamicObjectiveField(key = "sensacao", label = "Sensação desejada", type = "text", placeholder = "Ex: conforto, confiança, modernidade")
        ),
        "antes_depois" to listOf(
            DynamicObjectiveField(key = "o_que_mudou", label = "O que mudou?", type = "textarea", placeholder = "Descreva o antes e depois")
        ),
        "atendimento" to listOf(
            DynamicObjectiveField(key = "tipo_atendimento", label = "Tipo de atendimento", type = "text", placeholder = "Ex: consulta, avaliação, atendimento personalizado")
        ),
        "especialidade" to listOf(
            DynamicObjectiveField(key = "especialidade", label = "Especialidade", type = "text", placeholder = "Ex: ortodontia, estética facial, fisioterapia")
        ),
        "pet_servico" to listOf(
            DynamicObjectiveField(key = "servico_pet", label = "Serviço para pet", type = "text", placeholder = "Ex: banho, tosa, hidratação"),
            DynamicObjectiveField(key = "porte_pet", label = "Porte ou tipo de pet", type = "text", placeholder = "Ex: cães pequenos, gatos, todos os portes")
        ),
        "aulas" to listOf(
            DynamicObjectiveField(key = "tipo_aula", label = "Tipo de aula", type = "text", placeholder = "Ex: funcional, musculação, dança"),
            DynamicObjectiveField(key = "horarios", label = "Horários", type = "text", placeholder = "Opcional")
        ),
        "colecao" to listOf(
            DynamicObjectiveField(key = "nome_colecao", label = "Nome da coleção", type = "text", placeholder = "Ex: coleção verão"),
            DynamicObjectiveField(key = "pecas_destaque", label = "Peças em destaque", type = "textarea", placeholder = "Ex: vestidos, conjuntos, acessórios")
        ),
        "servico_auto" to listOf(
            DynamicObjectiveField(key = "servico_auto", label = "Serviço automotivo", type = "text", placeholder = "Ex: troca de óleo, alinhamento, lavagem"),
            DynamicObjectiveField(key = "condicao", label = "Condição ou benefício", type = "text", placeholder = "Ex: agendamento rápido, garantia, promoção")
        ),
        "matriculas" to listOf(
            DynamicObjectiveField(key = "curso_turma", label = "Curso ou turma", type = "text", placeholder = "Ex: infantil, inglês, técnico"),
            DynamicObjectiveField(key = "periodo", label = "Período", type = "text", placeholder = "Ex: matrículas abertas para 2026")
        ),
        "curso" to listOf(
            DynamicObjectiveField(key = "nome_curso", label = "Nome do curso", type = "text", placeholder = "Ex: inglês básico, informática, profissionalizante"),
            DynamicObjectiveField(key = "duracao", label = "Duração", type = "text", placeholder = "Opcional")
        ),
        "orcamento" to listOf(
            DynamicObjectiveField(key = "tipo_orcamento", label = "Tipo de orçamento", type = "text", placeholder = "Ex: orçamento grátis, visita técnica, sob medida")
        )
    )

    fun suggestions(query: String, limit: Int = 18): List<String> {
        val normalizedQuery = normalize(query)
        return ramos.distinct().filter { ramo ->
            if (isBlockedRamo(ramo)) return@filter false
            if (normalizedQuery.isBlank()) {
                true
            } else {
                normalize(ramo).contains(normalizedQuery) ||
                    ramoAliases[ramo].orEmpty().any { alias -> normalize(alias).contains(normalizedQuery) }
            }
        }.take(limit)
    }

    fun objectivesForRamo(ramo: String): List<CreateArtObjective> {
        if (isBlockedRamo(ramo)) return emptyList()

        val ramoKey = normalizeKey(ramo)
        if (ramoKey == "futebol") {
            return objetivosPorNicho["futebol"].orEmpty()
        }

        val category = categoryForRamo(ramo)
        return (objetivosPorNicho[ramoKey].orEmpty() +
            objetivosPorCategoria[category].orEmpty() +
            objetivosGerais).distinctBy { it.id }
    }

    fun characteristicsForRamo(ramo: String): List<CompanyCharacteristic> {
        if (isBlockedRamo(ramo)) return emptyList()

        val category = categoryForRamo(ramo)
        return (caracteristicasPorCategoria[category].orEmpty() + caracteristicasGerais)
            .distinctBy { it.id }
    }

    fun dynamicFieldsForObjective(objective: CreateArtObjective?): List<DynamicObjectiveField> {
        return camposDinamicosPorObjetivo[objective?.fields].orEmpty()
    }

    private fun categoryForRamo(ramo: String): String {
        val key = normalizeKey(ramo)
        ramoCategorias[key]?.let { return it }
        return categoriaKeywords.entries.firstOrNull { (_, keywords) ->
            keywords.any { keyword -> key.contains(keyword) }
        }?.key.orEmpty()
    }

    fun normalizeKey(value: String): String {
        return normalize(value).replace(Regex("[^a-z0-9]+"), "_").trim('_')
    }

    fun isBlockedRamo(value: String): Boolean {
        return normalizeKey(value) in blockedRamoKeys
    }

    private fun normalize(value: String): String {
        val decomposed = Normalizer.normalize(value.lowercase().trim(), Normalizer.Form.NFD)
        return decomposed.replace(Regex("\\p{Mn}+"), "")
    }
}
